### ISSUE TITLE
DNS failure results in catastrophic exception - handle to remove lock file

### ISSUE THREAD

**Issue by servilla** [PASTAplus/soh#2]
During a DNS error, a catastrophic exception occurred where the SOH applications exited without remove the lock file. This exception should be handled in a more eloquent fashion.

> 2019-09-06 13:10:17,840 [19810] ERROR    server.py: soh.asserts.server: [Errno -5] No address associated with hostname
> 2019-09-06 13:10:23,131 [19810] CRITICAL root: Traceback (most recent call last):
>   File "/home/pasta/soh/src/soh/health_check.py", line 428, in <module>
>     main(sys.argv)
>   File "/home/pasta/soh/src/soh/health_check.py", line 266, in main
>     quiet=quiet, notify=notify)
>   File "/home/pasta/soh/src/soh/health_check.py", line 76, in do_check
>     mailout.send_mail(subject=subject, msg=diagnostic, to=Config.ADMIN_TO)
>   File "/home/pasta/anaconda3/envs/soh/lib/python3.6/site-packages/soh/mailout.py", line 32, in send_mail
>     smtpObj = smtplib.SMTP('mail.hover.com', 587)
>   File "/home/pasta/anaconda3/envs/soh/lib/python3.6/smtplib.py", line 251, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/home/pasta/anaconda3/envs/soh/lib/python3.6/smtplib.py", line 336, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/home/pasta/anaconda3/envs/soh/lib/python3.6/smtplib.py", line 307, in _get_socket
>     self.source_address)
>   File "/home/pasta/anaconda3/envs/soh/lib/python3.6/socket.py", line 704, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>   File "/home/pasta/anaconda3/envs/soh/lib/python3.6/socket.py", line 745, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution

**Comment by servilla** [comment]
Added exception handing the mailout.send_mail call.
